# Generated by Django 4.1 on 2022-08-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='form_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
