# Generated by Django 4.1 on 2022-08-30 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_statement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
