# Generated by Django 4.1 on 2022-08-30 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0005_taxstatement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxStatement',
            new_name='InterestStatement',
        ),
    ]
