# Generated by Django 4.1 on 2022-08-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
