# Generated by Django 4.1 on 2022-08-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_loan_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='editable',
            field=models.CharField(choices=[('Not Applied', 'Not Applied'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('Updated', 'Updated')], default='Not Applied', max_length=14),
        ),
    ]
