# Generated by Django 4.1 on 2022-08-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_loan_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_as_read', models.BooleanField(verbose_name='Mark as Read')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('loan_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan', verbose_name='Loan User')),
            ],
            options={
                'verbose_name': 'Notification history',
                'verbose_name_plural': 'Notification histories',
            },
        ),
    ]
