# Generated by Django 4.1 on 2022-08-27 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0010_notificationhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='money_lender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_money_lender', to=settings.AUTH_USER_MODEL, verbose_name='Money Lender'),
            preserve_default=False,
        ),
    ]
