# Generated by Django 4.1 on 2022-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_notificationhistory_money_lender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
