# Generated by Django 4.1 on 2022-08-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_alter_notificationhistory_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='amount',
            field=models.PositiveIntegerField(default=2000, verbose_name='Loan Amount'),
            preserve_default=False,
        ),
    ]
