# Generated by Django 4.1 on 2022-08-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_notificationhistory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='mark_as_read',
            field=models.BooleanField(default=True, verbose_name='Mark as Read'),
        ),
    ]
