# Generated by Django 4.1 on 2022-08-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_notificationhistory_editable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationhistory',
            name='money_lender',
        ),
    ]
