# Generated by Django 4.1 on 2022-08-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_notificationhistory_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='mark_as_read',
            field=models.BooleanField(default=False, verbose_name='Mark as Read'),
        ),
    ]
