# Generated by Django 4.1 on 2022-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_profile', '0002_alter_user_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_bank_balance',
            field=models.PositiveBigIntegerField(default=40000),
            preserve_default=False,
        ),
    ]
