# Generated by Django 4.1 on 2022-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainsetting',
            name='email_address',
            field=models.EmailField(default=1, max_length=50, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
