# Generated by Django 4.1 on 2022-08-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_domainsetting_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainsetting',
            name='email_address',
        ),
        migrations.AddField(
            model_name='domainsetting',
            name='email_from',
            field=models.EmailField(default=1, max_length=50, verbose_name='Email From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domainsetting',
            name='email_to',
            field=models.EmailField(default='tajbink@gmail.com', max_length=50, verbose_name='Email To'),
            preserve_default=False,
        ),
    ]
