# Generated by Django 4.1 on 2022-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_remove_domainsetting_email_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('plain_text_html', models.TextField(verbose_name='Plain Text HTML')),
                ('notification_name', models.CharField(choices=[('New Loan Request', 'New Loan Request')], max_length=256)),
                ('plain_text_html_enable', models.BooleanField(help_text='This will ignore the message field content.', verbose_name='Plain Text HTML Enable')),
            ],
        ),
    ]
