# Generated by Django 4.1 on 2022-08-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_emailcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainsetting',
            name='email_to',
        ),
    ]
