# Generated by Django 4.1 on 2022-08-18 16:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_remove_domainsetting_email_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='message',
            field=ckeditor.fields.RichTextField(default='new'),
            preserve_default=False,
        ),
    ]
