# Generated by Django 4.1 on 2022-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_emailcontent_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='notification_name',
            field=models.CharField(choices=[('New Loan Request', 'New Loan Request'), ('New Loan Request Approve', 'New Loan Request Approve')], max_length=256),
        ),
    ]
