# Generated by Django 4.1 on 2022-08-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_alter_emailcontent_notification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='notification_name',
            field=models.CharField(choices=[('New Loan Request', 'New Loan Request'), ('New Loan Request Approved', 'New Loan Request Approved'), ('New Loan Request Rejected', 'New Loan Request Rejected')], max_length=256),
        ),
    ]
