# Generated by Django 4.1 on 2022-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_alter_emailcontent_notification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='notification_name',
            field=models.CharField(choices=[('New Loan Request', 'New Loan Request'), ('New Loan Request Approved', 'New Loan Request Approved'), ('New Loan Request Rejected', 'New Loan Request Rejected'), ('Loan Edit Request', 'Loan Edit Request'), ('Loan Edit Request Approved', 'Loan Edit Request Approved'), ('Loan Edit Request Rejected', 'Loan Edit Request Rejected')], max_length=256),
        ),
    ]
